---

version: "2.1"

services:

  code-server:

    image: lscr.io/linuxserver/code-server:latest

    container_name: code-server

    environment:

      - PUID=1000

      - PGID=1000

      - TZ=America/Los_Angeles

      - PASSWORD=Rafaelvm1! #optional

      - HASHED_PASSWORD= #optional

      - SUDO_PASSWORD=rafael #optional

      - SUDO_PASSWORD_HASH= #optional

      - PROXY_DOMAIN=code.superradlab.com #optional

      - DEFAULT_WORKSPACE=/config/workspace #optional

    volumes:

      - $PWD/config:/config

    ports:

      - 8443:8443

    restart: unless-stopped
